const assert = require('node:assert/strict');
const { randomUUID } = require('node:crypto');
module.exports = async ({ source, request, login, teacher, outsider, admin }) => {
  const base='/teacher/classes';
  const call=(path='',method='GET',body,token=teacher.accessToken)=>request(base+path,{method,body,token});
  assert.equal((await request(base)).status,401);
  for(const token of [outsider.accessToken,admin.accessToken]) assert.equal((await call('','POST',{name:'Denied'},token)).status,403);
  for(const body of [{name:''},{name:'   '},{name:null},{name:'x'.repeat(121)},{name:'bad\nname'},{name:'OK',teacherId:outsider.user.id},{name:'OK',joinCode:'HACK'}]) assert.equal((await call('','POST',body)).status,400);
  const created=await call('','POST',{name:'  سوم الف  '});
  assert.equal(created.status,201,JSON.stringify(created.data));
  const c=created.data;
  assert.equal(c.name,'سوم الف');assert.equal(c.teacherId,teacher.user.id);
  assert.equal(c.status,'active');assert.equal(c.archivedAt,null);assert.match(c.joinCode,/^[A-F0-9]{16}$/);
  assert.deepEqual((await call('/'+c.id)).data,c);
  assert.equal((await call('/invalid')).status,400);
  assert.equal((await call('/'+randomUUID())).status,404);
  let other=await login('class-other-teacher@example.com');
  await source.query("UPDATE users SET role='teacher',auth_version=auth_version+1 WHERE id=$1",[other.user.id]);
  other=await login('class-other-teacher@example.com');
  assert.ok((await call()).data.every(row=>row.teacherId===teacher.user.id));
  assert.deepEqual((await call('','GET',undefined,other.accessToken)).data,[]);
  for(const [path,method] of [['/'+c.id,'GET'],['/'+c.id+'/archive','POST'],['/'+c.id+'/join-code/rotate','POST']]) assert.equal((await call(path,method,undefined,other.accessToken)).status,404);
  const rotated=await call('/'+c.id+'/join-code/rotate','POST');
  assert.equal(rotated.status,201);assert.notEqual(rotated.data.joinCode,c.joinCode);
  assert.equal((await source.query('SELECT id FROM classes WHERE join_code=$1',[c.joinCode])).length,0);
  const concurrent=await Promise.all([call('/'+c.id+'/join-code/rotate','POST'),call('/'+c.id+'/join-code/rotate','POST')]);
  assert.ok(concurrent.every(r=>r.status===201));assert.notEqual(concurrent[0].data.joinCode,concurrent[1].data.joinCode);
  const persisted=(await call('/'+c.id)).data.joinCode;assert.ok(concurrent.some(r=>r.data.joinCode===persisted));
  await source.query('INSERT INTO class_memberships(class_id,student_id) VALUES ($1,$2)',[c.id,outsider.user.id]);
  const membership=await source.query('SELECT * FROM class_memberships WHERE class_id=$1',[c.id]);
  const race=await Promise.all([call('/'+c.id+'/archive','POST'),call('/'+c.id+'/join-code/rotate','POST')]);
  assert.equal(race[0].status,201);assert.ok([201,409].includes(race[1].status));
  const archived=(await call('/'+c.id)).data;
  assert.equal(archived.status,'archived');assert.equal(archived.joinCode,null);assert.ok(archived.archivedAt);
  assert.deepEqual((await call('/'+c.id+'/archive','POST')).data,archived);
  assert.equal((await call('/'+c.id+'/join-code/rotate','POST')).status,409);
  const ended=await source.query('SELECT * FROM class_memberships WHERE class_id=$1',[c.id]);
  assert.equal(ended.length,membership.length);
  assert.ok(ended[0].ended_at >= ended[0].joined_at);
  assert.deepEqual({...ended[0],ended_at:null},membership[0]);
  assert.equal((await request('/test-access/classes/'+c.id,{token:outsider.accessToken})).status,403);
  const {ClassesService}=require('../src/classes/classes.service');
  const {User}=require('../src/users/user.entity');
  const stale=await source.getRepository(User).findOneByOrFail({id:other.user.id});
  await source.query("UPDATE users SET role='student',auth_version=auth_version+1 WHERE id=$1",[other.user.id]);
  await assert.rejects(()=>new ClassesService(source).create(stale,'Denied after demotion'),/Session revoked/);
  console.log('PASS BE-05 class creation, validation, ownership, rotation/concurrency, archive/history and stale role rejection');
};
